# Generated by Django 2.0.3 on 2018-03-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20180321_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', height_field=120, upload_to='profile_image', width_field=80),
        ),
    ]
