# Generated by Django 2.0.3 on 2018-03-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180321_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='height',
            new_name='height_field',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='width',
            new_name='width_field',
        ),
    ]
