# Generated by Django 2.0.3 on 2018-03-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20180321_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='profile_image'),
        ),
    ]
